#ErrorTypes
errorType:
  business: "PRODUCTION_ORDER:WORKCENTER_NOT_ACCEPTABLE,MULE:DUPLICATE_MESSAGE,HTTP_CUSTOM:BUSINESS_ERROR,PRODUCT:INVALID_CHANNEL,PRODUCT:INVALID_CODE,PRODUCT:PRODUCT_NOT_FOUND,SF:BAD_REQUEST,SAP:ERROR,HTTP:BAD_REQUEST"
  technical: "KAFKA:CONNECTIVITY,KAFKA:RETRY_EXHAUSTED,KAFKA:INVALID_TOPIC,KAFKA:INVALID_TOPIC_PARTITION,KAFKA:INVALID_OFFSET,KAFKA:NOT_FOUND,KAFKA:TIMEOUT,KAFKA:ALREADY_COMMITED,KAFKA:COMMIT_FAILED,KAFKA:INVALID_CONNECTION,SALESFORCE:CONNECTIVITY,SALESFORCE:INVALID_AUTH,SALESFORCE:REQUEST_TIMEOUT,SALESFORCE:API_LIMIT_EXCEEDED,SALESFORCE:INVALID_FIELD,SALESFORCE:MALFORMED_QUERY,ALESFORCE:RETRY_EXHAUSTED,SALESFORCE:TIMEOUT,SALESFORCE:INVALID_INPUT,SALESFORCE:LIMIT_EXCEEDED,SALESFORCE:COMMUNICATION,FTP:ACCESS_DENIED,FTP:CANNOT_REACH,FTP:CONNECTION_TIMEOUT,FTP:CONNECTIVITY,FTP:FILE_ALREADY_EXISTS,FTP:FILE_DOESNT_EXIST,FTP:FILE_NOT_FOUND,FTP:ILLEGAL_PATH,FTP:INVALID_CREDENTIALS,FTP:UNKNOWN_HOST,FTP:SERVICE_NOT_AVAILABLE,SFTP:ACCESS_DENIED,SFTP:CONNECTION_TIMEOUT,SFTP:CONNECTIVITY,SFTP:FILE_ALREADY_EXISTS,SFTP:ILLEGAL_PATH,SFTP:INVALID_CREDENTIALS,SFTP:FILE_NOT_FOUND,SFTP:CANNOT_REACH,SFTP:UNKNOWN_HOST,SFTP:FILE_DOESNT_EXIST,SFTP:SERVICE_NOT_AVAILABLE,HTTP:CONNECTIVITY,HTTP:UNAUTHORIZED,HTTP:FORBIDDEN,HTTP:NOT_FOUND,HTTP:REQUEST_TIMEOUT,HTTP:INTERNAL_SERVER_ERROR,HTTP:TOO_MANY_REQUEST,HTTP:SERVICE_UNAVAILABLE,HTTP:TOO_MANY_REQUESTS,HTTP:TIMEOUT,MULE:RETRY_EXHAUSTED,HTTP:RETRY_EXHAUSTED,HTTP_CUSTOM:TECHNICAL_ERROR,HTTP:CLIENT_SECURITY,HTTP:SECURITY,HTTP:GATEWAY_TIMEOUT,HTTP:BAD_GATEWAY,DB:CANNOT_REACH,DB:CONNECTIVITY,MULE:CONNECTIVITY"
  skipReprocessErrors: "MULE:EXPRESSION,APIKIT:BAD_REQUEST,APIKIT:NOT_FOUND,APIKIT:METHOD_NOT_ALLOWED,APIKIT:NOT_ACCEPTABLE,APIKIT:NOT_IMPLEMENTED,APIKIT:UNSUPPORTED_MEDIA_TYPE"

reprocess: "true"

reconnection:
  frequency: "30000"
  attempt: "3"
  
error:
  dailyRetryCount: "5"

kafka:
  retryBackoffTimeout: "100"
  batchSize: "16"
  batchSizeUnit: "KB"
  bufferSize: "1000"
  bufferSizeUnit: "KB"
  clientDNSLookup: "USE_ALL_DNS_IPS"
  compressionType: "NONE"
  connectionsMaximumIdleTimeout: "540"
  connectionsMaximumIdleTimeUnit: "SECONDS"
  deliveryTimeout: "120"
  deliveryTimeoutTimeUnit: "SECONDS"
  lingerTime: "0"
  lingerTimeUnit: "SECONDS"
  maximumBlockTime: "60"
  maximumBlockTimeUnit: "SECONDS"
  maximumInFlightRequests: "5"
  maximumRequestSize: "1"
  maximumRequestSizeUnit: "MB"
  producerAck: "NONE"
  receiveBufferSize: "64" 
  receiveBufferSizeUnit: "KB" 
  retries: "1"
  retryBackoffTimeoutTimeUnit: "MILLISECONDS"
  sendBufferSize: "128"
  sendBufferSizeUnit: "KB" 
  requestTimeout: "30"
  requestTimeoutTimeUnit: "SECONDS"
  partitioner: "DEFAULT"